apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "*/2 * * * *"
  startingDeadlineSeconds: 120
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 5
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: docker.io/bitnami/postgresql:14.3.0-debian-10-r22
              command:
                - bash
                - -c
                - "pg_dump postgres"
              env:
                - name: PGHOST
                  value: psql-postgresql
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: postgres-password
                      name: psql-postgresql



