apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: limits
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 500m
    max:
      memory: 512Mi
      cpu: 1500m
    min:
      memory: 256Mi
      cpu: 10m
    type: Container
