apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
  - 00-namespace.yml
  - ingress.yml

  - manifests/loki.yml
  - manifests/promtail.yml
  - manifests/grafana.yml
