apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yml
  - 00-namespace.yml

patchesStrategicMerge:
  - patch-resource-limit.yml

configMapGenerator:
  - name: minio-env
    literals:
      - LOGGING_LEVEL=none

secretGenerator:
  - name: minio-env
    literals:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=nbusr123

namespace: minio-prd

images:
  - name: minio
    newName: minio/minio
    newTag: RELEASE.2021-02-01T22-56-52Z
