---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresql
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app_component: postgres
    environment: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: postgresql
  name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
      name: postgres
      nodePort: 30432
  selector:
    app_component: postgres
    environment: dev
